### ISSUE TITLE
Можно ли использовать отладку, когда сервер 1С на linux, и нет общей папки?

### ISSUE THREAD

**Issue by VoronyukM** [partizand/debug_external_dataprocessor#2]
Добрый день! Когда сервер 1С и конфигуратор был на windows, была общая папка, доступная из конфигуратора, и из обарботки, и действовали способом, похожим на описанный. Однако когда сервер 1С переехал на linux и админы отказались делать общую папку, а конфигуратор остался на win-машине, пришлось мучиться с открытием обработок вручную через файл-открыть для отладки.
Ваш способ, насколько понял, тоже подразумевает наличие общей папки, правильно?

**Comment by partizand** [comment]
Да, нужна общая папка. Пользоваться этой разработкой для клиент-сервера затруднительно.
